import { spawn } from 'node:child_process'
import { randomUUID } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { chromium } from 'playwright'

const projectRoot = resolve(import.meta.dirname, '..')
const frontendUrl = process.env.APP_URL || 'http://127.0.0.1:5173'
const apiUrl = process.env.API_URL || 'http://127.0.0.1:8000'
const screenshotDir = resolve(projectRoot, 'screenshots')
const runHeadless = process.env.PLAYWRIGHT_HEADLESS === '1'
const slowMo = Number.parseInt(process.env.PLAYWRIGHT_SLOW_MO || '2000', 10)
const startedProcesses = []
const steps = []

function logPass(message) {
  steps.push({ status: 'pass', message })
  console.log(`PASS ${message}`)
}

function logInfo(message) {
  console.log(`INFO ${message}`)
}

function fail(message) {
  steps.push({ status: 'fail', message })
  throw new Error(message)
}

function delay(ms) {
  return new Promise((resolveDelay) => setTimeout(resolveDelay, ms))
}

function createRandomEmail() {
  const token = randomUUID().replaceAll('-', '').slice(0, 12)
  return `automation-${token}@example.test`
}

async function canFetch(url) {
  try {
    const response = await fetch(url)
    return response.ok
  } catch {
    return false
  }
}

function startProcess(command, args, name) {
  let child

  const isWindowsCommand = command.endsWith('.cmd')

  try {
    child = spawn(isWindowsCommand ? 'cmd.exe' : command, isWindowsCommand ? ['/d', '/s', '/c', command, ...args] : args, {
      cwd: projectRoot,
      env: {
        ...process.env,
        VITE_API_BASE_URL: apiUrl,
        ALLOWED_ORIGINS: `${frontendUrl},http://localhost:5173,http://127.0.0.1:5173`
      },
      shell: false,
      stdio: ['ignore', 'pipe', 'pipe']
    })
  } catch (error) {
    throw new Error(`Could not start ${name} with ${command}: ${error.message}`)
  }

  child.on('error', (error) => {
    logInfo(`${name} failed to start: ${error.message}`)
  })

  child.stdout.on('data', (chunk) => {
    const output = chunk.toString().trim()
    if (output) {
      logInfo(`${name}: ${output}`)
    }
  })

  child.stderr.on('data', (chunk) => {
    const output = chunk.toString().trim()
    if (output) {
      logInfo(`${name}: ${output}`)
    }
  })

  child.on('exit', (code) => {
    if (code !== null && code !== 0) {
      logInfo(`${name} exited with code ${code}`)
    }
  })

  startedProcesses.push(child)
}

async function waitFor(url, label, timeoutMs = 30000) {
  const deadline = Date.now() + timeoutMs

  while (Date.now() < deadline) {
    if (await canFetch(url)) {
      logPass(`${label} is reachable`)
      return
    }
    await delay(500)
  }

  fail(`${label} did not become reachable at ${url}`)
}

async function ensureServers() {
  if (!(await canFetch(`${apiUrl}/api/status`))) {
    startProcess(
      resolve(projectRoot, 'venv', 'Scripts', 'python.exe'),
      ['-m', 'uvicorn', 'api.main:app', '--host', '127.0.0.1', '--port', '8000'],
      'api'
    )
  }

  if (!(await canFetch(frontendUrl))) {
    startProcess('npm.cmd', ['run', 'dev', '--', '--host', '127.0.0.1'], 'vite')
  }

  await waitFor(`${apiUrl}/api/status`, 'API')
  await waitFor(frontendUrl, 'Login page')
}

async function apiJson(path, options) {
  const response = await fetch(`${apiUrl}${path}`, options)
  if (!response.ok) {
    throw new Error(`${options?.method || 'GET'} ${path} returned ${response.status}`)
  }
  return response.json()
}

async function saveAutomationScreenshot() {
  const rows = steps
    .map((step) => `<li class="${step.status}"><strong>${step.status.toUpperCase()}</strong><span>${step.message}</span></li>`)
    .join('')
  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <style>
    body { margin: 0; background: #11110f; color: #fffefa; font: 16px/1.5 Arial, sans-serif; }
    main { width: 900px; padding: 48px; }
    h1 { margin: 0 0 10px; font: 42px/1.05 Georgia, serif; font-weight: 400; }
    p { margin: 0 0 28px; color: #cbc7bd; }
    ul { display: grid; gap: 10px; padding: 0; margin: 0; list-style: none; }
    li { display: grid; grid-template-columns: 90px 1fr; gap: 16px; padding: 12px 14px; border: 1px solid #3a3832; border-radius: 8px; background: #1a1916; }
    strong { color: #9fca7f; }
    .fail strong { color: #ff9f8c; }
    span { color: #f4f1ea; }
  </style>
</head>
<body>
  <main>
    <h1>Automation passed</h1>
    <p>Generated by <code>npm run automate</code>.</p>
    <ul>${rows}</ul>
  </main>
</body>
</html>`

  const browser = await chromium.launch({ headless: true })
  const page = await browser.newPage({ viewport: { width: 1000, height: 720 } })
  await page.setContent(html)
  await page.screenshot({ path: resolve(screenshotDir, 'automation.png'), fullPage: true })
  await browser.close()
}

async function main() {
  await mkdir(screenshotDir, { recursive: true })
  await ensureServers()

  await apiJson('/api/status', {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ status: 'live' })
  })
  logPass('Form status reset to Live')

  logInfo(runHeadless
    ? 'Opening Chromium in headless mode.'
    : 'Opening a visible Chromium window so you can watch the automation.')
  const browser = await chromium.launch({
    headless: runHeadless,
    slowMo: runHeadless ? 0 : slowMo
  })
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  const testEmail = createRandomEmail()

  try {
    const before = await apiJson('/api/submissions')
    logInfo(`Using random email: ${testEmail}`)

    await page.goto(frontendUrl, { waitUntil: 'networkidle' })
    await page.fill('#email', testEmail)
    await page.fill('#training-code', 'local-training-pass')
    await page.click('button[type="submit"]')
    await page.getByText("You're all set. This training submission has been recorded.").waitFor({ timeout: 10000 })
    logPass('Login form submitted successfully')

    const after = await apiJson('/api/submissions')
    const newSubmission = after.find((submission) => submission.email === testEmail)
    if (!newSubmission || after.length <= before.length) {
      fail('New submission was not returned by GET /api/submissions')
    }
    logPass('GET /api/submissions includes the new submission')

    await page.goto(`${frontendUrl}/admin`, { waitUntil: 'networkidle' })
    await page.getByText(testEmail).waitFor({ timeout: 10000 })
    logPass('Admin table shows the new submission')

    await page.getByRole('button', { name: /stop form/i }).click()
    await page.getByText('Stopped').waitFor({ timeout: 10000 })
    logPass('Stop button changed the form status to Stopped')

    await page.goto(frontendUrl, { waitUntil: 'networkidle' })
    await page.getByText('Training closed').waitFor({ timeout: 10000 })
    logPass('Login page shows the closed state after stopping')

    await page.goto(frontendUrl, { waitUntil: 'networkidle' })
    const closedVisible = await page.getByText('Training closed').isVisible()
    const formVisible = await page.locator('form.auth-card').isVisible().catch(() => false)
    if (!closedVisible || formVisible) {
      fail('Stopped form is not blocked on the login page')
    }
    logPass('Second submission attempt is blocked by the closed page')

    await page.setViewportSize({ width: 1440, height: 1000 })
    await apiJson('/api/status', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ status: 'live' })
    })
    await page.goto(frontendUrl, { waitUntil: 'networkidle' })
    await page.screenshot({ path: resolve(screenshotDir, 'login-desktop.png'), fullPage: true })
    logPass('Captured login-desktop.png')

    await page.setViewportSize({ width: 375, height: 900 })
    await page.goto(frontendUrl, { waitUntil: 'networkidle' })
    await page.screenshot({ path: resolve(screenshotDir, 'login-narrow.png'), fullPage: true })
    logPass('Captured login-narrow.png')

    await page.setViewportSize({ width: 1440, height: 1000 })
    await page.goto(`${frontendUrl}/admin`, { waitUntil: 'networkidle' })
    await page.getByText(testEmail).waitFor({ timeout: 10000 })
    await page.screenshot({ path: resolve(screenshotDir, 'admin.png'), fullPage: true })
    logPass('Captured admin.png')

    await apiJson('/api/status', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ status: 'stopped' })
    })
    await page.goto(frontendUrl, { waitUntil: 'networkidle' })
    await page.getByText('Training closed').waitFor({ timeout: 10000 })
    await page.screenshot({ path: resolve(screenshotDir, 'closed.png'), fullPage: true })
    logPass('Captured closed.png')

    await page.goto(`file://${resolve(projectRoot, 'out', 'email.html').replaceAll('\\', '/')}`, { waitUntil: 'load' })
    await page.screenshot({ path: resolve(screenshotDir, 'email.png'), fullPage: true })
    logPass('Captured email.png')
  } finally {
    await browser.close()
  }

  await saveAutomationScreenshot()
  logPass('Captured automation.png')
  console.log('Automation complete.')
}

main()
  .catch((error) => {
    console.error(`FAIL ${error.message}`)
    process.exitCode = 1
  })
  .finally(() => {
    for (const child of startedProcesses.reverse()) {
      child.kill()
    }
  })
